---
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  Env:
    Default: dev
    Type: String
    Description: Toutes les resources sont tagges et/ou prefixes par cet environnement

  VPCCIDR:
    Type: String
    Description: plage d'adresses IP pour le VPC
    MinLength: '9'
    MaxLength: '18'
    Default: 10.1.0.0/16
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    ConstraintDescription: "doit etre une plage d'IP CIDR valide de la forme x.x.x.x/x."

  VPCid:
    Type: AWS::EC2::VPC::Id
    Description: "Id d'un VPC existant"

  VPCname:
    Type: String
    Default: ap-sf-vpc
    AllowedValues:
      - ram-vpc
      - ap-prod-vpc
      - ap-sf-vpc
      - ap-preprod-vpc

  SUBid:
    Type: AWS::EC2::Subnet::Id
    Description: "Id d'un subnet existant"

  SUBname:
    Type: String
    Default: ap_sf_private_a
    AllowedValues:
      - ap-prod-private-a
      - ap-prod-private-b
      - ap-prod-private-c
      - ap-prod-pub-a
      - ap-prod-pub-b
      - ap-prod-pub-c
      - ap_preprod_private_a
      - ap_preprod_private_b
      - ap_preprod_private_c
      - ap_preprod_pub_a
      - ap_preprod_pub_b
      - ap_preprod_pub_c
      - ap_sf_private_a
      - ap_sf_private_b
      - ap_sf_private_c
      - ap_sf_pub_a
      - ap_sf_pub_b
      - ap_sf_pub_c

  SubnetCIDR:
    Type: String
    Description: plage d'adresses IP pour le Subnet
    MinLength: '9'
    MaxLength: '18'
    Default: 10.1.0.0/24
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    ConstraintDescription: "doit etre une plage d'IP CIDR valide de la forme x.x.x.x/x."


Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 
        Ref: VPCCIDR
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'true'
      InstanceTenancy: default
      Tags:
      - Key: Name
        Value: 
          Ref: VPCname
  Subnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: VPCid
      CidrBlock:
        Ref: SubnetCIDR
      AvailabilityZone: "us-east-1a"
      Tags:
      - Key: Name
        Value: 
         Ref: SUBid
...